const mongoose=require("mongoose");
const AddressSchema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"users",
        required:true,
    },
    fullName:{
        type:String,
        required:true
    },
    phoneNumber:{
        type:Number,
        required:true
    },
    Address:{
        type:String,
        required:true
    },
    Pincode:{
        type:Number,
        required:true
    },
    City:{
        type:String,
        require:true
    },
    State:{
        type:String,
        require:true
    }
});
module.exports=mongoose.model("Address",AddressSchema)